name: Ci Workflow

run-name: ${{ github.actor }} is testing out GitHub Actions

on: [push, workflow_dispatch]

jobs:

  ci-pipeline:

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code

        uses: actions/checkout@v4

      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."

      - name: Setup node
        uses: actions/setup-node@v4

      - run: npm ci && npm run prettier && npm run typecheck && npm run test && npm run build